Library_Management/Library_Management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('student.urls')),
]

Library_Management/student/urls.py
from django.urls import path
from student import views
urlpatterns = [
    path('',views.Home.as_view(),name='home'),
    path('author_create/',views.Author_Creation.as_view(),name='author_create'),
    path('book_create/',views.Book_Creation.as_view(),name='book_create'),
    path('book_update/<int:pk>/',views.Book_Update.as_view(),name='book_update'),
    path('book_detail/<int:pk>/',views.Book_Details.as_view(),name='book_detail'),
    path('book_list/',views.Book_List.as_view(),name='books'),
    path('book_delete/<int:pk>/',views.Book_Delete.as_view(),name='book_delete'),
]

Library_Management/student/models.py
from django.db import models

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    nationality = models.CharField(max_length=100, null=True, blank=True)
    biography = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    isbn = models.CharField(max_length=13, unique=True)
    publication_date = models.DateField()
    genre = models.CharField(max_length=100)

    def __str__(self):
        return self.title

class Borrower(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=15)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

class Borrowing(models.Model):
    borrower = models.ForeignKey(Borrower, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    borrowed_date = models.DateField(auto_now_add=True)
    due_date = models.DateField()
    returned = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.book.title} borrowed by {self.borrower.first_name} {self.borrower.last_name}'

Library_Management/student/forms.py
from django import forms
from .models import Author, Book, Borrower, Borrowing

class Author_Creation_Form(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
            'date_of_birth': forms.DateInput(attrs={'class': 'form-control', 'placeholder':'Date Of Birth'}),
            'nationality': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nationality'}),
            'biography': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'BioGraphy'}),
        }


class Book_Creation_Form(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'
        
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Book Title'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
            'isbn': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ISBN'}),
            'publication_date': forms.DateInput(attrs={'class': 'form-control', 'placeholder':'Published Date'}),
            'genre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Genre'}),
        }

Library_Management/student/views.py
#Django Imports
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView,DetailView
from .forms import Author_Creation_Form, Book_Creation_Form
from django.views import View
from .models import Author, Book, Borrower, Borrowing

# Create your views here.
class Home(View):
    def get(self, request):
        return render(request, 'student/home.html')
#Author Management:

class Author_Creation(CreateView):
    form_class = Author_Creation_Form
    template_name = 'student/author_creation.html'
    success_url = '/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

class Book_Creation(CreateView):
    model = Book
    form_class = Book_Creation_Form
    template_name = 'student/book_creation.html'
    success_url = '/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class Book_Update(UpdateView):
    model = Book
    form_class = Book_Creation_Form
    template_name = 'student/book_update.html'
    success_url = '/book_list/'


class Book_Details(DetailView):
    model = Book
    template_name = 'student/book_details.html'
    success_url = '/'


class Book_List(ListView):
    model = Book
    template_name = 'student/books.html'

class Book_Delete(DeleteView):
    model = Book
    template_name = 'student/book_delete.html'
    success_url = '/book_list/'

Library_Management/student/templates/student/author_creation.html
{% extends 'student/base.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <!-- <div class="mb-3">
        <div class="col-6"> -->
    <div class="row g-3 align-items-center">
        <div class="col-6">
        <label for="first_name" class="form-label">First Name</label>
        <input type="text" name="first_name" class="form-control" id="id_first_name" required="" >
    </div>
    </div>
    <div class="row g-3 align-items-center">
        <div class="col-6">
        <label for="last_name" class="form-label">Last Name</label>
        <input type="text" name="last_name" class="form-control" id="id_last_name" required="">
    </div>
    </div>
    <div class="row g-3 align-items-center">
        <div class="col-6">
            <label for="date_of_birth" class="form-label">Date of birth</label>
            <input type="date" name="date_of_birth" class="form-control" id="id_date_of_birth" required="">
        </div>
    </div>
    <div class="row g-3 align-items-center">
        <div class="col-6">
        <label for="nationality" class="form-label">Nationality</label>
        <input type="text" name="nationality" class="form-control" id="id_nationality" required="">
    </div>
    </div>
    <div class="row g-3 align-items-center">
        <div class="col-6">
        <label for="biography" class="form-label">Biography</label>
        <input type="text" name="biography" class="form-control" id="id_biography" required="">
    </div>
    </div>
   
    <button type="submit" class="mt-3 btn btn-primary">Submit</button>
</form>

{% endblock %}

Library_Management/student/templates/student/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Library Management System{% endblock %}</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    {% block extra_css %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Library</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'books' %}">Books</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'author_create' %}">Authors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Borrowers</a>
                </li>
            </ul>
        </div>
    </nav>
    
    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>
    
    <footer class="bg-light text-center text-lg-start mt-4">
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            &copy; 2024 Library Management System
        </div>
    </footer>

    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    {% block extra_js %}
    {% endblock %}
</body>
</html>

Library_Management/student/templates/student/book_creation.html
{% extends 'student/base.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="row g-3 align-items-center">
        <div class="col-6">
        <label for="title" class="form-label">Book Title</label>
        <input type="text" name="title" class="form-control" id="id_title" required="" >
    </div>
    </div>
    <div class="row g-3 align-items-center">
        <div class="col-6">
        <label for="author" class="form-label">Author</label>
        <select name="author" class="form-control" id="id_author" required>
            <!-- for default value  -->
            <option value="" {% if form.author.value == '' %}selected{% endif %}>Select an Author</option>
             <!-- end of for default value  -->
            {% for author in form.author.field.queryset %}
                <option value="{{ author.id }}" {% if form.author.value == author.id|stringformat:"s" %}selected{% endif %}>
                    {{ author }}
                </option>
            {% endfor %}
        </select>
    </div>
    </div>
    <div class="row g-3 align-items-center">
        <div class="col-6">
            <label for="isbn" class="form-label">ISBN</label>
            <input type="text" name="isbn" class="form-control" id="id_isbn" required="">
        </div>
    </div>
    <div class="row g-3 align-items-center">
        <div class="col-6">
        <label for="publication_date" class="form-label">Publication Date</label>
        <input type="date" name="publication_date" class="form-control" id="id_publication_date" required="">
    </div>
    </div>
    <div class="row g-3 align-items-center">
        <div class="col-6">
        <label for="genre" class="form-label">Genre</label>
        <input type="text" name="genre" class="form-control" id="id_genre" required="">
    </div>
    </div>
   
    <button type="submit" class="mt-3 btn btn-primary">Submit</button>
</form>

{% endblock %}

Library_Management/student/templates/student/book_delete.html
{% extends 'student/base.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <h1>Are you Sure you Want To Delete!</h1>
   

    <input type="submit" class="mt-3 btn btn-danger" value="Delete">
    <a href="{% url 'book_update' book.id %}" class="mt-3 btn btn-primary">Cancle</a>
</form>

{% endblock %}

Library_Management/student/templates/student/book_details.html
{% extends 'student/base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Student Dashboard</div>
                <div class="card-body">
                    {{ book.title }}
                    {{ book.author }}
                    {{ book.isbn }}
                    {{ book.publication_date }}
                    {{ book.genre }}        
                </div>
            </div>
            <a href="{% url 'book_update' book.id %}" class="mt-3 btn btn-primary">Update</a>
            <a href="{% url 'book_delete' book.id %}" class="mt-3 btn btn-primary">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

Library_Management/student/templates/student/book_update.html
{% extends 'student/base.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
   {{form.as_p}}
   
    <button type="submit" class="mt-3 btn btn-primary">Update</button>
    <a href="{% url 'book_detail' book.id %}" class="mt-3 btn btn-primary">Back</a>
</form>

{% endblock %}

Library_Management/student/templates/student/books.html
{% extends 'student/base.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="table">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Sr. No</th>
                            <th scope="col">Book Title</th>
                            <th scope="col">Author</th>
                            <th scope="col">ISBN</th>
                            <th scope="col">Publication Date</th>
                            <th scope="col">Genre</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        
                        {% for book in book_list %}        
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{book.title}}</td>
                            <td>{{book.author}}</td>
                            <td>{{book.isbn}}</td>
                            <td>{{book.publication_date}}</td>
                            <td>{{book.genre}}</td>
                            <td><a href="{% url 'book_detail' book.id %}" class="btn  btn-primary">View</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        {% endblock %}

Library_Management/student/templates/student/home.html
{% extends 'student/base.html' %}

{% block content %}
<h1>Welcome Home</h1>
{% endblock %}